name: Reusable Workflow

on:
  workflow_dispatch:
    inputs:  &workflow_inputs
      string_input:
        required: true
        type: string
  workflow_call:
    inputs: *workflow_inputs
    outputs:
      workflow_output1:
        description: "The first job output"
        value: ${{ jobs.job1.outputs.output1 }}
      workflow_output2:
        description: "The second job output"
        value: ${{ jobs.job1.outputs.output2 }}


jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=${{ inputs.string_input }}" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Sleep
        shell: bash
        run: sleep 30s
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
